In [1]:
import pandas as pd
df = pd.read_excel('subject1_trial1.xlsx')
df1= pd.read_excel('subject1_trial2.xlsx')
df2= pd.read_excel('subject1_trial3.xlsx')
df3= pd.read_excel('subject1_trial4.xlsx')
df4= pd.read_excel('subject1_trial5.xlsx')
df5= pd.read_excel('subject1_trial6.xlsx')
df6= pd.read_excel('subject1_trial7.xlsx')
df7= pd.read_excel('subject1_trial8.xlsx')
df8= pd.read_excel('subject1_trial9.xlsx')
df9= pd.read_excel('subject1_trial10.xlsx')

In [2]:
print(df)
print(df1)
print(df2)
print(df3)
print(df4)
print(df5)
print(df6)
print(df7)
print(df8)
print(df9)

            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    48793.10     13  38028.17     7  26666.67       0  29045.80     -1
1    49132.95     13  38028.17     7  26666.67       0  29045.80     -1
2    48793.10     13  37803.74     7  26798.56       0  29346.15      0
3    49132.95     13  38028.17     7  26405.70      -1  29195.40     -1
4    49132.95     13  38028.17     7  26535.71       0  29045.80     -1
..        ...    ...       ...   ...       ...     ...       ...    ...
345  77435.91     46  64130.43    41  52000.00      42  56428.57     33
346  77435.91     46  64130.43    41  51626.50      41  56000.00     33
347  78189.66     47  64671.53    42  52000.00      42  56428.57     33
348  78189.66     47  64671.53    42  51626.50      41  56000.00     33
349  78189.66     47  64671.53    42  51626.50      41  56428.57     33

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    32625.00      8      0     0       0     0      0      0
1    32803.35      8      0     0       0     0      0      0
2    32625.00      8      0     0       0     0      0      0
3    32803.35      8      0     0       0     0      0      0
4    32803.35      8      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
345  38483.41     16      0     0       0     0      0      0
346  37803.74     15      0     0       0     0      0      0
347  37803.74     15      0     0       0     0      0      0
348  38028.17     15      0     0       0     0      0      0
349  38028.17     15      0     0       0     0      0      0

[350 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    49824.56    -12  38947.37    -6  27610.29       1  29805.45      0
1    49132.95    -14  38947.37    -6  27610.29       1  29960.94      0
2    49824.56    -12  38483.41    -6  27610.29       1  29805.45      0
3    49476.75    -13  38714.29    -6  27610.29       1  29960.94      0
4    49824.56    -12  38714.29    -6  27610.29       1  29805.45      0
..        ...    ...       ...   ...       ...     ...       ...    ...
342  82999.99     39  63071.43    30  53540.37      45  58657.72     36
343  84722.23     42  62042.25    29  52378.05      43  52378.05     28
344  72500.00     22  54339.63    17  47471.91      34  43560.21     17
345  61538.46      5  45000.00     3  38028.17      18  36500.00      8
346  60068.50      3  42731.96     0  30920.00       6  34094.83      5

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    32803.35     -3      0     0       0     0      0      0
1    32625.00     -3      0     0       0     0      0      0
2    32625.00     -3      0     0       0     0      0      0
3    32625.00     -3      0     0       0     0      0      0
4    32803.35     -3      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
342  36289.59      2      0     0       0     0      0      0
343  37142.86      3      0     0       0     0      0      0
344  35874.44      1      0     0       0     0      0      0
345  35466.67      0      0     0       0     0      0      0
346  35466.67      0      0     0       0     0      0      0

[347 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    51626.50    -10  40394.09    -3  29960.94       5  32098.77      2
1    52000.00     -9  40643.56    -3  29960.94       5  32272.73      2
2    52378.05     -8  40643.56    -3  29960.94       5  32448.13      3
3    52000.00     -9  40394.09    -3  29960.94       5  32448.13      3
4    52000.00     -9  40147.05    -4  30117.64       5  32098.77      2
..        ...    ...       ...   ...       ...     ...       ...    ...
344  75250.01     27  59591.84    25  49476.75      38  54339.63     31
345  75966.39     28  60068.50    26  48793.10      37  54746.84     31
346  75966.39     28  59591.84    25  49476.75      38  54339.63     31
347  76694.91     29  60551.72    26  48793.10      37  53937.50     30
348  76694.91     29  60551.72    26  48793.10      37  54339.63     31

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    34285.71     -1      0     0       0     0      0      0
1    34094.83     -1      0     0       0     0      0      0
2    34285.71     -1      0     0       0     0      0      0
3    34285.71     -1      0     0       0     0      0      0
4    34094.83     -1      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
344  37581.39      4      0     0       0     1      0      0
345  37581.39      4      0     0       0     1      0      0
346  37581.39      4      0     0       0     1      0      0
347  37361.11      3      0     0       0     1      0      0
348  37581.39      4      0     0       0     1      0      0

[349 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    53540.37     -7  44414.89     2  35874.44      15  36081.08      7
1    53937.50     -6  45000.00     3  35669.64      14  36081.08      7
2    54339.63     -5  44705.88     2  35466.67      14  36289.59      8
3    53937.50     -6  44705.88     2  35466.67      14  36081.08      7
4    53540.37     -7  44126.98     1  35265.48      14  36081.08      7
..        ...    ...       ...   ...       ...     ...       ...    ...
340  78956.52     33  60068.50    26  50176.47      39  55159.23     32
341  81339.28     36  60551.72    26  51626.50      41  52378.05     28
342  66343.29     13  52000.00    13  45901.64      32  41928.93     15
343  58200.00      0  42731.96     0  36926.60      16  35466.67      7
344  56862.75     -1  42193.88    -1  31084.34       6  32803.35      3

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    34672.49      0      0     0       0     0      0      0
1    34672.49      0      0     0       0     0      0      0
2    34672.49      0      0     0       0     0      0      0
3    34478.26      0      0     0       0     0      0      0
4    34868.42      0      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
340  36712.33      2      0     0       0     0      0      0
341  37581.39      4      0     0       0     0      0      0
342  36081.08      1      0     0       0     0      0      0
343  35466.67      0      0     0       0     0      0      0
344  35265.48      0      0     0       0     0      0      0

[345 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    51626.50    -10  39182.69    -5  27200.00       0  30117.64      0
1    51257.49    -10  39182.69    -5  26798.56       0  30117.64      0
2    51257.49    -10  38714.29    -6  26931.41       0  29960.94      0
3    51626.50    -10  39182.69    -5  26931.41       0  30117.64      0
4    51626.50    -10  39182.69    -5  27200.00       0  30275.59      0
..        ...    ...       ...   ...       ...     ...       ...    ...
345  78956.52     33  55159.23    18  47150.84      34  46519.34     21
346  62042.25      6  43560.21     0  38254.72      19  35669.64      7
347  59121.62      1  41928.93    -1  30920.00       6  32983.20      3
348  58657.72      1  41928.93    -1  28314.61       2  31926.23      2
349  58200.00      0  41928.93    -1  27749.08       1  31417.00      1

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    32983.20     -3      0     0       0     0      0      0
1    32983.20     -3      0     0       0     0      0      0
2    32983.20     -3      0     0       0     0      0      0
3    33164.56     -3      0     0       0     0      0      0
4    33164.56     -3      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
345  37361.11      3      0     0       0     0      0      0
346  35265.48      0      0     0       0     0      0      0
347  35466.67      0      0     0       0     0      0      0
348  34672.49      0      0     0       0     0      0      0
349  34094.83     -1      0     0       0     0      0      0

[350 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    45901.64    -19  36081.08   -10  25769.23      -2  28029.74     -2
1    46208.79    -18  36289.59   -10  28029.74       1  28314.61     -2
2    45901.64    -19  36712.33    -9  28171.64       1  28897.34     -1
3    45901.64    -19  36500.00    -9  27888.89       1  28603.78     -1
4    45901.64    -19  36712.33    -9  27335.77       0  28603.78     -1
..        ...    ...       ...   ...       ...     ...       ...    ...
346  80530.97     35  60551.72    26  50176.47      39  55159.23     32
347  82999.99     39  59591.84    25  51257.49      41  55159.23     32
348  82162.16     38  59591.84    25  50176.47      39  48125.00     23
349  66917.30     14  50176.47    10  43842.11      28  38483.41     10
350  58657.72      1  43560.21     0  36289.59      15  34868.42      6

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    31417.00     -5      0     0       0     0      0      0
1    31417.00     -5      0     0       0     0      0      0
2    31417.00     -5      0     0       0     0      0      0
3    31585.37     -5      0     0       0     0      0      0
4    31417.00     -5      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
346  36500.00      2      0     0       0     0      0      0
347  38947.37      6      0     0       0     0      0      0
348  37581.39      4      0     0       0     0      0      0
349  35874.44      1      0     0       0     0      0      0
350  35669.64      1      0     0       0     0      0      0

[351 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    52378.05     -8  40895.52    -3  28171.64       1  30756.97      0
1    52760.73     -8  40643.56    -3  28171.64       1  30920.00      1
2    52000.00     -9  40643.56    -3  28171.64       1  30920.00      1
3    52760.73     -8  40895.52    -3  28171.64       1  30756.97      0
4    52760.73     -8  40643.56    -3  28171.64       1  30756.97      0
..        ...    ...       ...   ...       ...     ...       ...    ...
336  89320.39     49  66343.29    35  56428.57      49  61538.46     40
337  87428.57     46  65220.59    33  54339.63      46  58657.72     36
338  73852.45     25  60068.50    26  47796.61      35  44126.98     18
339  63597.12      8  45901.64     4  33905.58      11  35466.67      7
340  54339.63     -5  38947.37    -6  26276.60      -1  29651.16      0

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    34285.71     -1      0     0       0     0      0      0
1    34868.42      0      0     0       0     0      0      0
2    34478.26      0      0     0       0     0      0      0
3    34672.49      0      0     0       0     0      0      0
4    34672.49      0      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
336  38714.29      6      0     0       0     1      0      0
337  42193.88     11      0     0       0     0      0      0
338  38028.17      4      0     0       0     0      0      0
339  33531.91     -2      0     0       0     0      0      0
340  32272.73     -4      0     0       0     0      0      0

[341 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    46833.33     11  35874.44     4  25275.86      -2  28171.64     -2
1    46833.33     11  35669.64     4  25154.64      -3  28029.74     -2
2    46833.33     11  36081.08     5  25034.25      -3  28171.64     -2
3    46833.33     11  35874.44     4  25154.64      -3  28171.64     -2
4    46833.33     11  35874.44     4  25154.64      -3  28029.74     -2
..        ...    ...       ...   ...       ...     ...       ...    ...
343  73170.73     41  54746.84    29  49824.56      38  54339.63     31
344  73170.73     41  54339.63    28  50532.55      39  54339.63     31
345  73852.45     42  54746.84    29  50532.55      39  54746.84     31
346  76694.91     45  55159.23    29  49476.75      38  47471.91     22
347  63597.12     30  44414.89    15  39660.20      21  36712.33      8

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    31084.34      5      0     0       0     0      0      0
1    31250.00      6      0     0       0     0      0      0
2    30920.00      5      0     0       0     0      0      0
3    30756.97      5      0     0       0     0      0      0
4    31084.34      5      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
343  36081.08     12      0     0       0     0      0      0
344  36289.59     13      0     0       0     0      0      0
345  36712.33     13      0     0       0     0      0      0
346  36289.59     13      0     0       0     0      0      0
347  34478.26     10      0     0       0     0      0      0

[348 rows x 16 columns]
            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    56428.57     -2  41666.67    -2  27610.29       1  32625.00      3
1    56428.57     -2  41666.67    -2  27472.53       0  32625.00      3
2    56428.57     -2  41407.03    -2  27749.08       1  32448.13      3
3    56428.57     -2  41666.67    -2  27749.08       1  32448.13      3
4    56428.57     -2  41407.03    -2  27888.89       1  32448.13      3
..        ...    ...       ...   ...       ...     ...       ...    ...
351  82162.16      2  67500.00    37  53937.50      45  59591.84     38
352  84722.23      1  65777.77    34  53937.50      45  52760.73     29
353  71190.47      4  54339.63    17  46519.34      33  41666.67     14
354  63597.12      1  45000.00     3  38028.17      18  36081.08      7
355  62553.19      0  43560.21     0  33347.46      10  34285.71      5

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    36500.00      2      0     0       0     0      0      0
1    35874.44      1      0     0       0     0      0      0
2    36081.08      1      0     0       0     0      0      0
3    36500.00      2      0     0       0     0      0      0
4    36289.59      2      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
351  36500.00      2      0     0       0     0      0      0
352  38028.17      4      0     0       0     0      0      0
353  36712.33      2      0     0       0     0      0      0
354  36289.59      2      0     0       0     0      0      0
355  35874.44      1      0     0       0     0      0      0

[356 rows x 16 columns]

            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    36081.08     -1  29498.07    -3  21671.83      -9  23651.32     -8
1    36081.08     -1  29498.07    -3  21671.83      -9  23431.37     -8
2    36712.33      0  29498.07    -3  21574.07      -9  23540.98     -8
3    36712.33      0  29195.40    -3  21574.07      -9  23651.32     -8
4    36289.59      0  29346.15    -3  21476.92      -9  23651.32     -8
..        ...    ...       ...   ...       ...     ...       ...    ...
338  79736.84     49  60068.50    36  52760.73      43  58200.00     36
339  78189.66     47  61041.67    37  53540.37      45  58657.72     36
340  82162.16     52  58657.72    34  53540.37      45  50532.55     26
341  61538.46     28  44705.88    16  41666.67      24  36926.60      8
342  58657.72     24  40643.56    11  29651.16       4  32098.77      2

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    25894.74     -1      0     0       0     0      0      0
1    25644.60     -1      0     0       0     0      0      0
2    25894.74     -1      0     0       0     0      0      0
3    25769.23     -1      0     0       0     0      0      0
4    25769.23     -1      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
338  35874.44     12      0     0       0     1      0      0
339  36081.08     12      0     0       0     0      0      0
340  35874.44     12      0     0       0     0      0      0
341  34868.42     11      0     0       0     0      0      0
342  33905.58      9      0     0       0     0      0      0

[343 rows x 16 columns]

In [3]:
frames1 = pd.concat([df, df1,df2, df3,df4, df5, df6, df7, df8, df9],ignore_index=False)
print(frames1)

            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    48793.10     13  38028.17     7  26666.67       0  29045.80     -1
1    49132.95     13  38028.17     7  26666.67       0  29045.80     -1
2    48793.10     13  37803.74     7  26798.56       0  29346.15      0
3    49132.95     13  38028.17     7  26405.70      -1  29195.40     -1
4    49132.95     13  38028.17     7  26535.71       0  29045.80     -1
..        ...    ...       ...   ...       ...     ...       ...    ...
338  79736.84     49  60068.50    36  52760.73      43  58200.00     36
339  78189.66     47  61041.67    37  53540.37      45  58657.72     36
340  82162.16     52  58657.72    34  53540.37      45  50532.55     26
341  61538.46     28  44705.88    16  41666.67      24  36926.60      8
342  58657.72     24  40643.56    11  29651.16       4  32098.77      2

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    32625.00      8      0     0       0     0      0      0
1    32803.35      8      0     0       0     0      0      0
2    32625.00      8      0     0       0     0      0      0
3    32803.35      8      0     0       0     0      0      0
4    32803.35      8      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
338  35874.44     12      0     0       0     1      0      0
339  36081.08     12      0     0       0     0      0      0
340  35874.44     12      0     0       0     0      0      0
341  34868.42     11      0     0       0     0      0      0
342  33905.58      9      0     0       0     0      0      0

[3480 rows x 16 columns]

In [4]:
frames2=frames1.drop(frames1.iloc[:, 18:26], inplace = True, axis = 1)

In [5]:
print(frames1)

            R  PINKY       R.1  RING       R.2  MIDDLE       R.3  INDEX  \
0    48793.10     13  38028.17     7  26666.67       0  29045.80     -1
1    49132.95     13  38028.17     7  26666.67       0  29045.80     -1
2    48793.10     13  37803.74     7  26798.56       0  29346.15      0
3    49132.95     13  38028.17     7  26405.70      -1  29195.40     -1
4    49132.95     13  38028.17     7  26535.71       0  29045.80     -1
..        ...    ...       ...   ...       ...     ...       ...    ...
338  79736.84     49  60068.50    36  52760.73      43  58200.00     36
339  78189.66     47  61041.67    37  53540.37      45  58657.72     36
340  82162.16     52  58657.72    34  53540.37      45  50532.55     26
341  61538.46     28  44705.88    16  41666.67      24  36926.60      8
342  58657.72     24  40643.56    11  29651.16       4  32098.77      2

          R.4  THUMB  pinky  ring  middle  palm  index  thumb
0    32625.00      8      0     0       0     0      0      0
1    32803.35      8      0     0       0     0      0      0
2    32625.00      8      0     0       0     0      0      0
3    32803.35      8      0     0       0     0      0      0
4    32803.35      8      0     0       0     0      0      0
..        ...    ...    ...   ...     ...   ...    ...    ...
338  35874.44     12      0     0       0     1      0      0
339  36081.08     12      0     0       0     0      0      0
340  35874.44     12      0     0       0     0      0      0
341  34868.42     11      0     0       0     0      0      0
342  33905.58      9      0     0       0     0      0      0

[3480 rows x 16 columns]

In [6]:
frames3=frames1.drop(['R','R.1','R.2','R.3','R.4'], axis = 1)

In [7]:
print(frames3)

     PINKY  RING  MIDDLE  INDEX  THUMB  pinky  ring  middle  palm  index  \
0       13     7       0     -1      8      0     0       0     0      0
1       13     7       0     -1      8      0     0       0     0      0
2       13     7       0      0      8      0     0       0     0      0
3       13     7      -1     -1      8      0     0       0     0      0
4       13     7       0     -1      8      0     0       0     0      0
..     ...   ...     ...    ...    ...    ...   ...     ...   ...    ...
338     49    36      43     36     12      0     0       0     1      0
339     47    37      45     36     12      0     0       0     0      0
340     52    34      45     26     12      0     0       0     0      0
341     28    16      24      8     11      0     0       0     0      0
342     24    11       4      2      9      0     0       0     0      0

     thumb
0        0
1        0
2        0
3        0
4        0
..     ...
338      0
339      0
340      0
341      0
342      0

[3480 rows x 11 columns]

In [8]:
class_list=[]
for p in frames3[['pinky','ring','middle','palm','index','thumb']].values:
    c=0
    for i in range(0,5):
        if(p[i]!=0):
            c=c+1
    if(c>=2):
        for f_sum in p:
            f_sum+=f_sum
        if(f_sum>3):
            class_list.append('No Slip')
            
        else:
            class_list.append('Slip')
    else:
        class_list.append('Slip')

In [9]:
frames3['Class']=class_list

In [10]:
print(frames3)

     PINKY  RING  MIDDLE  INDEX  THUMB  pinky  ring  middle  palm  index  \
0       13     7       0     -1      8      0     0       0     0      0
1       13     7       0     -1      8      0     0       0     0      0
2       13     7       0      0      8      0     0       0     0      0
3       13     7      -1     -1      8      0     0       0     0      0
4       13     7       0     -1      8      0     0       0     0      0
..     ...   ...     ...    ...    ...    ...   ...     ...   ...    ...
338     49    36      43     36     12      0     0       0     1      0
339     47    37      45     36     12      0     0       0     0      0
340     52    34      45     26     12      0     0       0     0      0
341     28    16      24      8     11      0     0       0     0      0
342     24    11       4      2      9      0     0       0     0      0

     thumb Class
0        0  Slip
1        0  Slip
2        0  Slip
3        0  Slip
4        0  Slip
..     ...   ...
338      0  Slip
339      0  Slip
340      0  Slip
341      0  Slip
342      0  Slip

[3480 rows x 12 columns]

In [11]:
print(frames3.Class)

0      Slip
1      Slip
2      Slip
3      Slip
4      Slip
       ...
338    Slip
339    Slip
340    Slip
341    Slip
342    Slip
Name: Class, Length: 3480, dtype: object

In [12]:
X = frames3.drop('Class', axis=1)
y = frames3['Class']

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [20]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly')
svclassifier.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [21]:
y_pred = svclassifier.predict(X_test)

In [22]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[107  13]
 [ 22 554]]
              precision    recall  f1-score   support

     No Slip       0.83      0.89      0.86       120
        Slip       0.98      0.96      0.97       576

    accuracy                           0.95       696
   macro avg       0.90      0.93      0.91       696
weighted avg       0.95      0.95      0.95       696